# Site
repository: CODEMCD/resume
# favicon: images/favicon.ico

# Personal info
name: 박성범
title: 백엔드 엔지니어 지망생
email: psbum1609@gmail.com
website: https://velog.io/@codemcd

# Social links
# twitter_username: CODEMCD
github_username: CODEMCD
# dribbble_username: jekyll
# facebook_username: devbeginner
# flickr_username: jekyll
# linkedin_username: CODEMCD
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  현재는 백엔드 개발자를 준비하면서, <mark>성장</mark> 에 매우 관심이 많습니다.

  컴퓨터공학과를 졸업한 후 우아한테크코스와 POCU 아카데미 C++ 강좌를 수료하였습니다.

  OOP와 클린 코드의 중요성을 이해하고 이를 적용하려 노력하며,

  테스트 코드를 작성하는 것을 당연하게 생각합니다. TDD에도 관심이 많습니다.

  배운 지식과 개발을 하며 생긴 이슈는 GITHUB와 블로그에 기록하고 있습니다.

  항상 과거의 나에게 고칠 점을 찾아 성장하기 위해 회고를 하고 있습니다.

  속력보다는 <mark>좋은 방향</mark> 으로 성장하는 개발자가 되고 싶습니다.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
- [Over-10 스터디](https://github.com/Over-10-Study)
  - 개발 관련 스터디
  - 활동 기간 2019.07 ~ 현재
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
